### ISSUE TITLE
About the E-book readers suggestions

### ISSUE THREAD

**Issue by adonese** [VoLuong/Awesome-Linux-Software#104]
I find your list to be really cool! One thing I found very useful and I highly recommend others to try is WPS Suite.

I've tried foxit reader (I'm using foxit version 2.3). It is very slow at startup and it generally takes a lot of CPU amount. I really do not know whether it is a problem related to me, or their new versions of it. Foxit used to very cool, and it is a lot close to Adobe things. One thing I really didn't like about Foxit is, that they do not have presentation mode.
I've also tried Okular. While it is RAM and CPU friendly, its UI is quite missed-up. The icons are ugly, you can not remove some panels. Okular has a presentation mode, but on the other hand their font is quite ugly. I mean, when I use chrome, or foxit I get a clear and a nice font, however when using Okular the font becomes quite different.

Evince is very cool, it is simple, fast, has presentation view, preserve your font (does exactly what a simple pdf reader should do). Don't get fool by its simplicity, it is very powerful though.

Google chrome has a nice pdf viewer itself! compared to Foxit, it really doesn't use that much of CPU or RAM (Ok, chrome is draining your RAM anyway, it is not its pdf reader fault).

**Comment by VoLuong** [comment]
> One thing I found very useful and I highly recommend others to try is WPS Suite.   

It's already on the list 👍
 
> It is very slow at startup and it generally takes a lot of CPU amount. 

I think this is your specific problem. I have been using Foxit reader for a long time and there are not even 1 single error with it, except that some features are missing compared to Windows' version.  

> I've also tried Okular. While it is [...] becomes quite **different.**  

Sorry but I have never noticed this. I found Okular to be "functional" and not anything more than that ( the aesthetic part may be worse for some people though )

> Google chrome has a nice pdf viewer itself!  

Cannot recommend this though. It is too simple and naive way of reading pdf ^_^ 

_I myself use qpdf heavily for reading pdf. It's lightweight, fast, functional, packed with features. For editing them, I stick with MasterPdf Editor._
