### ISSUE TITLE
Misleading Editors-CLI/GUI division

### ISSUE THREAD

**Issue by PiotrOrzechowski** [VoLuong/Awesome-Linux-Software#109]
I think it is better not to split _Editors_ section into _Editors-CLI_ and _Editors-GUI_, as was introduced in #107. Both Emacs and ViM have GUI as well, yet are classified as CLI-only tools, which is misleading. The fix is either to mention Emacs and ViM in both sections or even better, to revert back to single _Editors_ section. Also, there are CLI and GUI web browsers, music players, etc. This way many categories should have separate CLI/GUI sections.

**Comment by VoLuong** [comment]
Thank you for your warning. 
Let me explain a few things 👍  At first, I consider they are far more famous being used with CLI. Therefore, I decided that the decision to split them is kinda reasonable as it will highlight the power and the distinctiveness of these editors. 
However, your argument is right. It is obvious that we can start both of these editors in GUI mode.  I am merging them back to one category in the next commit.

**Comment by VoLuong** [comment]
9e1a7cbce6097fc6cf4ef3178b13b8dd7b6cfde0  @PiotrOrzechowski

**Comment by bhajneet** [comment]
GUI versions of vim and emacs usually differ from their CLI counterparts. To me it looks as though 3 CLI programs are "hidden" in a larger list of GUI programs. Either way should be fine. A good reader will see all options.

**Comment by VoLuong** [comment]
@bhajneet  I totally understand your idea. But as these programs have an option for GUI, which maybe 3 of us in this issue here would never use and care, we are not to disguise them from the readers 😃

**Comment by PiotrOrzechowski** [comment]
> which maybe 3 of us in this issue here would never use and care

@VoLuong: Hm, [Spacemacs](http://spacemacs.org), which is a distribution of Emacs, looks awesome in GUI mode. ;) Much better than in terminal, probably due to color palette.

**Comment by VoLuong** [comment]
@PiotrOrzechowski eyyy, why don't you make a PR to add that to the list 😆

**Comment by PiotrOrzechowski** [comment]
@VoLuong: It's 4 AM here and I'm sleepy. ;) Thanks for resolving #109.
