### ISSUE TITLE
Marlin seems to be abandoned

### ISSUE THREAD

**Issue by PiotrOrzechowski** [VoLuong/Awesome-Linux-Software#113]
Marlin seems to be abandoned project, at least according to [this](https://superuser.com/questions/1099756/how-to-install-marlin-file-manger-in-ubuntu-16-04/1128762#1128762).

**Comment by VoLuong** [comment]
I double checked that. So yeah, it seems true that marlin isn't continued anymore. 89c3aeda6c1cd988d9c780d00b4888ac71b6a7be
