### ISSUE TITLE
Add FeedReader

### ISSUE THREAD

**Issue by bil-elmoussaoui** [VoLuong/Awesome-Linux-Software#115]
Hey, 
FeedReader is one of the top RSS reader applications on Linux
On Github: https://github.com/jangernert/FeedReader
Website: https://jangernert.github.io/FeedReader/

**Comment by VoLuong** [comment]
@bil-elmoussaoui  Hi, please give me sometimes to test your application. Thank you for your suggestion.
Btw, why don't you pack it in an apt repository or snap :question:  You have an aversion on Ubuntu based distro ? :rofl:  Cuz right now I don't think it's worth installing the whole flatpak just to run one application (for most users)

**Comment by bil-elmoussaoui** [comment]
@VoLuong We had several issues with Launchpad, there's a contributor who works on getting a snap package on work. We do use the latest Gtk stuff (Gtk 3.22+), which is sadly not available yet on any stable Ubuntu distro...

**Comment by VoLuong** [comment]
@bil-elmoussaoui  I do feel your pain. I have built the application from source. It runs perfectly. You are now on the list 4f275e0 . 
I like this very much.  I do highly suggest that you guys spread the apps on some news page. omg-ubuntu and itsfoss are good places to start with. Also try to have the snappy version of the app. Snap is now a trend (IMO), and a lot of users out there (end-user, to be exact) really doesn't like to go through such many steps or build from source.
Again, great apps. Thanks for suggesting it here (Personally, I will keep using it more ).

**Comment by bil-elmoussaoui** [comment]
@VoLuong It's up for the writers to look for new good apps, and for the devs to write code:P I have already tried to reach out the guys on OMGUbuntu but no article was written.. so nothing i can do about it!:(
