### ISSUE TITLE
Add Hardcode-Tray

### ISSUE THREAD

**Issue by bil-elmoussaoui** [VoLuong/Awesome-Linux-Software#116]
Hardcode-Tray is a simple Python/bash script, that allows the user to replace those ugly colored tray icons with monochrome ones. We already have the support for more than 70+ applications, and we are working to fix more stuff in the future! 

Built by Linux community for the community! The tool is suggested by some great Linux icon themes out there as Numix, Papirus !
The tool link : https://github.com/bil-elmoussaoui/Hardcode-Tray
Thanks

**Comment by VoLuong** [comment]
Apply on Xubuntu 16.04.2 :-? Nothing happens. 
Requires 155MB when installing :-? And it automatically installs Inkscape too :cry:  
Am i doing something wrong here? 
![image](https://cloud.githubusercontent.com/assets/15828926/23655631/5673cd3c-0368-11e7-9a74-e0bd31812dbe.png)

**Comment by bil-elmoussaoui** [comment]
It picks the icons from the current theme you're using, see the README. You might want to try Papirus or Numix if you want a complete support or just use `hardcode-tray --theme Papirus`or `hardcode-tray --theme Numix` which will use one of the themes to look for icons. The script does not provide any icon, as forcing users to use the icons provided by the script won't fix the actual issue. 
Those packages shouldn't be included. You can follow the manual installation method. Inkscape is used to convert SVG icons to PNG ones, you can use any other tool that's supported by the script (CairoSVG, Inkscape, ImageMagick, Librsvg, rsvgconvert...)

**Comment by VoLuong** [comment]
@bil-elmoussaoui OKay. Give me some time for another try :yellow_heart:

**Comment by bil-elmoussaoui** [comment]
Take your time, just ping me if you have any issue and i will fix it as soon as i'm in front of my laptop :)

**Comment by VoLuong** [comment]
9347aac

**Comment by bil-elmoussaoui** [comment]
:heart:
