### ISSUE TITLE
games list is outdated

### ISSUE THREAD

**Issue by Translator5** [VoLuong/Awesome-Linux-Software#123]
the game list is totally outdated!
desura rip
csgo ... 
you can add there circa 1/4 of all non-free steamOS games!

**Comment by VoLuong** [comment]
Hi, sorry for the late reply, my computer was in a repair shop when you opened this issue. I will add a small warning that these games may be outdated, does that sound ok? Although i dont play game that much, the last time i tested them out, they still work fine.
