### ISSUE TITLE
Atom appears twice

### ISSUE THREAD

**Issue by LYF610400210** [VoLuong/Awesome-Linux-Software#42]
Atom appears twice. Do you consider removing one of them?

**Comment by VoLuong** [comment]
Ahhhh. Thank you for your noticing. Yeah at first I put them in both sections on purpose but now I am planning to remove it in either section but it remain a question to myself which section I should remove it from.
Sublime and VSCode are in the same case :<

**Comment by VoLuong** [comment]
Ok I removed 1 now/
