### ISSUE TITLE
Add corebird, qpdfview, phototonic, mypaint, sakura

### ISSUE THREAD

**Issue by smdrz** [VoLuong/Awesome-Linux-Software#44]
corebird is native gtk+ twitter desktop client

URL: http://corebird.baedert.org/
source : https://github.com/baedert/corebird

qpdf is pdf viewer

URL: https://launchpad.net/qpdfview

phototonic is image viewer and organizer

URL: https://github.com/oferkv/phototonic

mypaint is a paint program for use with graphics tablets
URL: http://mypaint.org/about/
source: https://github.com/mypaint/mypaint

sakura is a minimal gtk+ terminal
URL: https://launchpad.net/sakura

**Comment by VoLuong** [comment]
Thank you. I went through all the suggestions. They are all nice. Added now
