### ISSUE TITLE
gitbook table  of contents

### ISSUE THREAD

**Issue by tnga** [VoLuong/Awesome-Linux-Software#63]
actually there isn't really a difference between read it here or at gitbook. However it will be better that topic can be organize as gitbook way of table of contents, so that readers benefits of it useful navigation sidebar :wink:

**Comment by VoLuong** [comment]
> However it will be better that topic can be organize as gitbook way of table of contents, so that readers benefits of it useful navigation sidebar :wink:

Yeah thank you  i thought about it but I am on final exam so currently I have no time for that .

> actually there isn't really a difference between read it here or at gitbook.

yes for us there is no difference but for some users ( the normal one ), they keep complaining to me what is github why post a pdf file here (lol) how can i download your guide etc so i make a gitbook link for them. Now when they open it they will see a page of what they need only hahaa
