### ISSUE TITLE
A translated version

### ISSUE THREAD

**Issue by alim0x** [VoLuong/Awesome-Linux-Software#75]
Thanks for your nice work :+1: 
I translated the list into Chinese, hope it will be helpful  :  )

[Awesome-Linux-Software-zh_CN](https://github.com/alim0x/Awesome-Linux-Software-zh_CN)

**Comment by ChrisLeeGit** [comment]
Wow, nice job. It's really a pity that I didn't find out your repo before. Anyway, I've done the same job. :(

**Comment by VoLuong** [comment]
Thank you you guys. Since I dont know Chinese , I cant fully understand what you guys wrote but hope you guys do it great . Thank you.

**Comment by VoLuong** [comment]
By the way can you make a merge request ? 
Like adding a link to your fork in my original Readme.MD or make a folder in my repo then merge yours. Idk, just suggesting :D

**Comment by VoLuong** [comment]
@ChrisLeeGit  (y) nice job too https://github.com/ChrisLeeGit/awesome-linux-software-cn

**Comment by alim0x** [comment]
@ChrisLeeGit :+1: Your work also great!  I think you can add your work to the readme, too  : )

@VoLuong I have updated the readme

**Comment by VoLuong** [comment]
Thank you guys. Are people using Linux a lot in CHina?

**Comment by alim0x** [comment]
No... Most desktop users don't use Linux. I think it's the same as other countries 😂

**Comment by VoLuong** [comment]
My country is next to your country haha . Not most people use linux but a certain amount ;)
