### ISSUE TITLE
The other Chinese version based on your repo.

### ISSUE THREAD

**Issue by ChrisLeeGit** [VoLuong/Awesome-Linux-Software#77]
To tell the truth, before I decided to translate this list, I really didn't realize that there was another Chinese version on GitHub. I did search on the GitHub with the keyword like "awesome-linux-software", "awesome-linux-software-cn", but that repo was not in the results returned. :)

I started my repo based on yours, and I want to add something more that are best for Chinese Linux Users.:)

Anyway, thanks for your nice job! If possible, you could also add my version to your README file.

**Comment by jp1017** [comment]
@ChrisLeeGit 非常棒，已推荐到 gank.io

**Comment by VoLuong** [comment]
No problem. I added a link to your list beside the other guy ;)

**Comment by ChrisLeeGit** [comment]
Thanks!

**Comment by VoLuong** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: 
<fun fact> I would never know you are Chinese if it wouldn't for the previous issue :laughing:  Thank you for contributing to my repo :+1:
