### ISSUE TITLE
recommendation "Franz"

### ISSUE THREAD

**Issue by EssaAlshammri** [VoLuong/Awesome-Linux-Software#83]
http://meetfranz.com/

a chat app

**Comment by VoLuong** [comment]
OMG i use it everyday but forgot to add it here. Enormous Mistake. Thanks for your suggestion sir. will add in the next commit

**Comment by alim0x** [comment]
@VoLuong I would appreciate if you add new app item in the same position in zh_CN readme, English item is ok, so I can get rid of check every commit where the new item is : ) That will be helpful to me to maintain~

**Comment by VoLuong** [comment]
@alim0x  Ok got it. I will do that from now on ;)

**Comment by alim0x** [comment]
@VoLuong Thanks~ :+1:
